version: '3'
services:
  es0:
    #image: elasticsearch:8.13.4
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0-SNAPSHOT
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - ./config:/usr/share/elasticsearch/config

